language: php
os: linux

php:
  - 7.4

env:
  global:
    - DEPLOY_REGION=ap-northeast-1

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - mv ./.env.example ./.env

install:
  - composer install --prefer-dist

script:
  - composer run test

notifications:
  email: false
  slack:
    on_success: never
    rooms:
      secure: "d9opjVnTB06RT/F4p8V0sgbd3J2XHaDQzqbM7MesJtTL4+5gXSr6B4wJisxwwM9QuJKebWCivBN8J5N8Bz5NRNDRISl57rQsgVoqolsuH9y70GEOcDyAeToRjzlNpXce6Pmo8kEjVKndE8tAQcmKNfNSFKFoN4Xc3eLUoBjzCfLK2bnAohMdP0zZro0TLXooYDPXu6n02SUBSpTKWUyj8XXwHzgAnoX4nQD6UyGmS90sv93wEqxsL2UpuhkgEcHDhRrUQyjyGdQT0wY4QFWhnEC0LAozIu/vMSXZ8RnEMd36GDs//i7N0EFCepUq4v754YByWCJEf2ewxqpDdYZbYBhjbBJs3ySbSI1xcrjlNLu0ctGnSnzrTVuivqBVAiCeOa34K0FnabsNRQoXsUXgO3H+zJQubEMvsU9Un3hC4xLiA86Pi2OX0FkKbLa3gLcnAFYwwEtt+1gULIq9kt7ZlBpzKo/RzjbGWCQVJO7W+m72aN8Hd/dBNjFlMnI57GKY6pQuAxnt6V7dyMTYfLLjo5RksKwhHXo+Gvy+VU7wTW8IB/LNVJRCKqQaGDX6KrfCuONDh2xBgqxthIpc4KS6Lsqkvgb9UoAtPiEKVF2+06QfAF4t7Zd67SXXIsZsPi7oRdevNStxtAbWh7a4jYffCz2vRUFkljPq5/gsrByK7Yg="

before_deploy:
  - composer install --optimize-autoloader --no-dev
  - mkdir -p .CodeDeploy
  - zip -rq .CodeDeploy/latest.zip app bootstrap database public resources routes storage vendor appspec.yml scripts .env

deploy:
  - provider: s3
    access_key_id: &aws_access_id_key
      secure: "KUgC3avzoOxEai2+0YLWKXKZ6aV3/XAUxRMj/DQspYfLAajj0TxPMt2jIQufMUZgGa00gTuVEXYs9nAOeeaJEQ7JFo7NC/cCHosUR2NSjpYDUHsrKEL2EaIFGK7xmKzHb7Yhx4KwqDPBhFXsKXU1tMfG/jsLqiQlgEQjXGdJsvlgyeYAwzizGvpMvgh+c/pWLOhHUv/zEZB/woxdDs7HMsG7X+J02cJm0l30z/BEKctNrBiCjKtIwDeCBPAYPQf/2wrTBPSMlmQd1sn5e2kOy0WTYCw/yaUGJwhuaqFnCHZhmPpq5l4i2pXTZrcj5M8cWGevmp1SAOe/CQe48+F+pwt+RBLV5Ivaafa8gERxpKQNnJ4lelOHnzj60IPVl9GB1hCoVCFdFaOS2/M4EASEMYLnJaZmeXCSrcuN0Rp0VumWMff+Ld3jk0MxOBHRCT8jxaLNchPfJ70wa4udm92UqMqr3OubDmVHkkBXqOqQU41XGW0fCDACPCbQEfUPEyK9ZrH5qHGBYPuBjgTzy/fehxqzYe517NwLQvZvXuvWEexp/33qtpmNEcOV0Skhb66C6H1kt+wDzQHfQNGU6Pk7Yp5vNlJVHhL5OOmq85HuyTsQUjWf6UDbivzLtXNs8/kPguZQobsn39cFDI0+VoeKB34Buw1RnslwAMqX4gYg0dU="
    secret_access_key: &aws_secret_key
      secure: "j7Na+dltq3BlYEpmZIpkgm8Gf2Kk0tTFl28heAsKgd0PwTJ3HZIjZKNU7EAFKkYBwOFuhRpKmVPPIyz3MTog9CtT1zzF1t5tp531MWfBxQVTMXPOSTO8ND8g0FscKHnqbF6BKEdzRRZGhnDa+MgdsNWdSoIVVMFsCQWTjPUIaTDQSWABm+hvfCO1I85M/e9ibqlNm4JWm1786ywEW9F11Pb+1KMZeokShwv7h1Som1W53HXqCR3u2mXUlwbvehRex0EcDi89sa9YTfCYZ8uAVPTqyIDhBstns5PLtZ1F9gEWKqeBbt4nl9f+1VTcOoOvkkA0aQrJRRr5alJXaM+nxC2YAZAKhLseo+Zz0Qcv/fRU3/WFwJxbGQu2STBwwamA9xvWLa87p2BYlNhLVTUmBSaN6oO7V3Q3Qo8c3eoLnor+dsjt7EXZ3PLXxhcN1aYLuwflfK1oiX6EDoVK2rapkf0RVM6LVmjXDQEt/TVdUZvwa2WPQa3hG1o4HMfT1IrbGMs2+LLksZ/T7C+UH3NECa64Wb5NA5sWniW8Ta1qLrTy27bpJWEfLKOJb9qeUyFCOTxSawgnh1dMePuoPssSRJld7RqGorQs+QjLLxiIkRowL6JQZCmBVSSmJtnoLV4yIKX5X2mDzR4t88+CoxtuI1GA3/+rlD01vR6clhRzvaI="
    bucket: &deployment_bucket awscodedeploywithautosca-codedeploymentbucket072a-1otat3gez9j4j
    local_dir: .CodeDeploy
    skip_cleanup: true
    region: ${DEPLOY_REGION}
    on: &deploy_branch
      branch: master
  - provider: codedeploy
    access_key_id: *aws_access_id_key
    secret_access_key: *aws_secret_key
    bucket: *deployment_bucket
    key: latest.zip
    application: LumenApp
    deployment_group: Master
    region: ${DEPLOY_REGION}
    on: *deploy_branch
